name: fruitfly
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.1
  fl_chart: ^0.68.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.3
  change_app_package_name: ^1.1.0
  image_picker: ^1.1.2
  intl:
  velocity_x: ^4.2.1
  rating_dialog: ^2.0.4
  flutter_easyloading: ^3.0.5
  flutter_stripe: ^10.1.1
  flutter_widget_from_html: ^0.15.1
  firebase_core: ^3.1.0
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^15.0.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  cached_network_image: ^3.3.1
  timeago: ^3.6.1
  syncfusion_flutter_charts: ^26.2.14
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  rxdart: ^0.27.7


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/
  - assets/images/
  - assets/icons/

  uses-material-design: true

